# Generated by Django 5.0.7 on 2025-03-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_previousquestionpaper_user_studymaterial_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='template',
            name='student_name',
        ),
    ]
